spring.application.name=spring-boot-rocketmq

rocketmq.name-server: localhost:9876
rocketmq.producer.group: order-producer-group
rocketmq.producer.send-message-timeout: 3000
rocketmq.producer.retry-times-when-send-failed: 2
rocketmq.producer.retry-times-when-send-async-failed: 2
