server:
  port: 3333

spring:
  # profiles:
    # prod-生产 / uat-预发布 / test-测试 / dev-开发
    # active: prod
  datasource:
    test:
#      name: app
#      type: com.alibaba.druid.pool.DruidDataSource
#      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
#      url: jdbc:sqlserver://192.168.0.134;databasename=app
#      username: test
#      password: bpmlink
      name: test
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: ljh
      password: 123456
      initialSize: 1
      minIdle: 1
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      filters: stat
    demo:
      name: demo
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/demo?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: ljh
      password: 123456
      initialSize: 1
      minIdle: 1
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      filters: stat
  devtools:
    livereload:
      enabled: false
    restart:
      #设置那个目录的文件需要restart
      additional-paths: src/main/resources/static/static/html
      #排除那个目录的文件不需要restart
      #exclude:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss      #日期格式化
    serialization:
      indent_output: true                 #格式化输出
      fail_on_empty_beans: false          #忽略无法转换的对象
    default-property-inclusion: non_empty #设置空如何序列化
    deserialization:
      fail_on_unknown_properties: false   #允许对象忽略json中不存在的属性
    parser:
      allow_unquoted_control_chars: true  #允许出现特殊字符和转义符
      allow_single_quotes: true           #允许出现单引号

logging:
  file: logs/springboot.log
  level:
    springboot: debug
    org.springfromework.web: info