# Common Application Properties\uFF1Ahttps://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#appendix.application-properties
# \u914D\u7F6E\u6587\u4EF6\u8BE6\u89E3\uFF1Ahttps://blog.didispace.com/spring-boot-learning-21-1-3/
# Relaxed-Binding-2.0\uFF1Ahttps://github.com/spring-projects/spring-boot/wiki/Relaxed-Binding-2.0
# 2.5\u7248\u672C\u540E\u6570\u636E\u811A\u672C\u521D\u59CB\u5316\u7684\u53D8\u52A8\uFF1Ahttps://blog.didispace.com/spring-boot-learning-25-3-13/

############################################################
#
# Server \u670D\u52A1\u7AEF\u76F8\u5173\u914D\u7F6E
# https://blog.csdn.net/pan_junbiao/article/details/105951817
#
############################################################
server.port=3333
server.servlet.context-path=/
server.ip=43.136.102.115
#server.ip=10.0.8.8

############################################################
#
# profiles \u914D\u7F6E
# Spring Boot 2.4 \u5BF9\u591A\u73AF\u5883\u914D\u7F6E\u7684\u652F\u6301\u66F4\u6539\uFF1Ahttps://blog.didispace.com/spring-boot-learning-24-1-4/
# Spring Boot 2.4 \u7248\u672C\u524D\u540E\u7684\u5206\u7EC4\u914D\u7F6E\u53D8\u5316\u53CA\u5BF9\u591A\u73AF\u5883\u914D\u7F6E\u7ED3\u6784\u7684\u5F71\u54CD\uFF1Ahttps://blog.didispace.com/spring-boot-learning-24-1-5/
# active\uFF1Ahttps://yulaiz.com/spring-boot-maven-profiles/
#
############################################################
# prod-\u751F\u4EA7 | uat-\u9884\u53D1\u5E03 | test-\u6D4B\u8BD5 | dev-\u5F00\u53D1
#spring.profiles.active=@profileActive@
spring.profiles.active=hikari
spring.profiles.include=mybatis

############################################################
#
# servlet \u914D\u7F6E
#
############################################################
spring.servlet.encoding.charset=UTF-8
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=50MB

############################################################
#
# devtools \u914D\u7F6E
# \u5F53\u7C7B\u8DEF\u5F84\u4E0A\u7684\u6587\u4EF6\u53D1\u751F\u66F4\u6539\u65F6\uFF0C\u5E94\u7528\u7A0B\u5E8F\u5C31\u4F1A\u81EA\u52A8\u91CD\u542F\u3002
# \u4F7F\u7528 JRebel \u65F6\uFF0C\u81EA\u52A8\u91CD\u542F\u5C06\u88AB\u7981\u7528\uFF0C\u4EE5\u652F\u6301\u52A8\u6001\u7C7B\u91CD\u65B0\u52A0\u8F7D\u3002
# \u4F7F\u7528 AspectJ weaving \u65F6\uFF0C\u4E0D\u652F\u6301\u81EA\u52A8\u91CD\u542F\u3002
# @see DevToolsProperties
# Developer Tools\uFF1Ahttps://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#using.devtools
# Hot Swapping\uFF1Ahttps://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#howto.hotswapping
#
############################################################
spring.devtools.restart.enabled=true
# \u662F\u5426\u542F\u7528\u5F00\u53D1\u5C5E\u6027\u9ED8\u8BA4\u503C\uFF1Ahttps://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#using.devtools.property-defaults
spring.devtools.add-properties=true
# \u6392\u9664\u8DEF\u5F84\uFF1Ahttps://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#using.devtools.restart.excluding-resources
spring.devtools.restart.exclude=static/**,templates/**
# \u76D1\u63A7\u5176\u5B83\u8DEF\u5F84\uFF1Ahttps://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#using.devtools.restart.watching-additional-paths
spring.devtools.restart.additional-paths=src/main/java/springboot
# LiveReload\uFF0C\u6BCF\u5F53\u53D1\u751F\u66F4\u65B0\u65F6\uFF0C\u81EA\u52A8\u89E6\u53D1\u6D4F\u89C8\u5668\u5237\u65B0
spring.devtools.livereload.enabled=true
# \u53EA\u6709\u9759\u6001\u8D44\u6E90\u66F4\u6539\u624D\u89E6\u53D1\u6D4F\u89C8\u5668\u5237\u65B0
spring.devtools.remote.restart.enabled=false

############################################################
#
# banner \u914D\u7F6E
# 3.x \u4E0D\u652F\u6301\u56FE\u7247 banner
#
############################################################
#spring.banner.image.location=classpath:static/public/img/people/NoharaSinnosuke.png
#spring.banner.image.pixelmode=TEXT

############################################################
#
# redis \u914D\u7F6E
# 3.x-  spring.redis.x
# 3.x   spring.data.redis.x
#
############################################################
spring.data.redis.host=${server.ip}
spring.data.redis.port=6379
spring.data.redis.password=123456
# \u6570\u636E\u5E93\u7D22\u5F15\uFF08\u9ED8\u8BA4\u4E3A0\uFF09
spring.data.redis.database=0
# \u8FDE\u63A5\u6C60\u6700\u5927\u8FDE\u63A5\u6570\uFF08\u4F7F\u7528\u8D1F\u503C\u8868\u793A\u6CA1\u6709\u9650\u5236\uFF09
spring.data.redis.lettuce.pool.max-active=32
# \u8FDE\u63A5\u6C60\u6700\u5927\u963B\u585E\u7B49\u5F85\u65F6\u95F4\uFF08\u4F7F\u7528\u8D1F\u503C\u8868\u793A\u53EF\u4E00\u76F4\u963B\u585E\uFF09
spring.data.redis.lettuce.pool.max-wait=-1
# \u8FDE\u63A5\u6C60\u6700\u5927\u7A7A\u95F2\u8FDE\u63A5\uFF08\u4F7F\u7528\u8D1F\u503C\u8868\u793A\u6CA1\u6709\u9650\u5236\uFF09
spring.data.redis.lettuce.pool.max-idle=8
# \u8FDE\u63A5\u6C60\u6700\u5C0F\u7A7A\u95F2\u8FDE\u63A5\uFF08minIdle \u548C timeBetweenEvictionRuns \u5747\u4E3A\u6B63\u503C\u624D\u751F\u6548\uFF09
spring.data.redis.lettuce.pool.min-idle=2
spring.data.redis.lettuce.shutdown-timeout=100

############################################################
#
# influxDB \u914D\u7F6E
#
############################################################
#spring.influx.url=http://localhost:8086
#spring.influx.user=admin
#spring.influx.password=12345678

############################################################
#
# jackson \u914D\u7F6E
#
############################################################
# \u65E5\u671F\u683C\u5F0F\u5316
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
# \u65F6\u533A
spring.jackson.time-zone=GMT+8
# \u8BBE\u7F6E\u7A7A\u5982\u4F55\u5E8F\u5217\u5316
spring.jackson.default-property-inclusion=NON_EMPTY
# \u683C\u5F0F\u5316\u8F93\u51FA
spring.jackson.serialization.indent-output=true
# \u5FFD\u7565\u65E0\u6CD5\u8F6C\u6362\u7684\u5BF9\u8C61
spring.jackson.serialization.fail-on-empty-beans=false
# \u5141\u8BB8\u5BF9\u8C61\u5FFD\u7565 json \u4E2D\u4E0D\u5B58\u5728\u7684\u5C5E\u6027
spring.jackson.deserialization.fail-on-unknown-properties=false

############################################################
#
# \u9759\u6001\u8D44\u6E90\u914D\u7F6E
# @see WebMvcProperties
# @see WebProperties.Resources
# Static Content\uFF1Ahttps://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#features.developing-web-applications.spring-mvc.static-content
#
############################################################
spring.mvc.static-path-pattern=/**
spring.web.resources.static-locations=classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:F://
spring.web.resources.chain.strategy.content.enabled=true
spring.web.resources.chain.strategy.content.paths=/**
spring.web.resources.chain.strategy.fixed.enabled=true
spring.web.resources.chain.strategy.fixed.paths=/img/ico
spring.web.resources.chain.strategy.fixed.version=v2

############################################################
#
# freemarker \u9759\u6001\u8D44\u6E90\u914D\u7F6E
# @see FreeMarkerProperties
# https://blog.csdn.net/qq_45794678/article/details/102999519
#
############################################################
spring.freemarker.template-loader-path=classpath:/templates/
spring.freemarker.suffix=.ftl
spring.freemarker.check-template-location=true
spring.freemarker.expose-request-attributes=true
spring.freemarker.expose-session-attributes=true
# \u7ED9 RequestContext \u5C5E\u6027\u547D\u540D
spring.freemarker.request-context-attribute=request
spring.freemarker.charset=UTF-8
spring.freemarker.content-type=text/html
# \u5173\u95ED\u7F13\u5B58\uFF0C\u5373\u65F6\u5237\u65B0\uFF0C\u4E0A\u7EBF\u751F\u4EA7\u73AF\u5883\u9700\u8981\u6539\u4E3A true
spring.freemarker.cache=false

############################################################
#
# thymeleaf \u9759\u6001\u8D44\u6E90\u914D\u7F6E
# @see ThymeleafProperties
#
############################################################
# \u662F\u5426\u5728\u5448\u73B0\u6A21\u677F\u4E4B\u524D\u68C0\u67E5\u6A21\u677F\u662F\u5426\u5B58\u5728\uFF0C\u9ED8\u8BA4 true
spring.thymeleaf.check-template=true
# \u662F\u5426\u68C0\u67E5\u6A21\u677F\u4F4D\u7F6E\u662F\u5426\u5B58\u5728\uFF0C\u9ED8\u8BA4 true
spring.thymeleaf.check-template-location=true
# \u5728\u6784\u5EFAURL\u65F6\u88AB\u9644\u52A0\u5230\u89C6\u56FE\u540D\u79F0\u7684\u524D\u7F00\uFF0C\u9ED8\u8BA4 classpath:/templates/
spring.thymeleaf.prefix=classpath:/templates/
# \u5728\u6784\u5EFAURL\u65F6\u9644\u52A0\u5230\u89C6\u56FE\u540D\u79F0\u7684\u540E\u7F00\uFF0C\u9ED8\u8BA4 .html
spring.thymeleaf.suffix=.html
# \u6A21\u677F\u5E94\u7528\u7684\u6A21\u677F\u6A21\u5F0F\u3002\u53C2\u89C1 TemplateMode\uFF0C\u9ED8\u8BA4 HTML
spring.thymeleaf.mode=HTML
# \u6A21\u677F\u6587\u4EF6\u7F16\u7801\uFF0C\u9ED8\u8BA4 UTF-8
spring.thymeleaf.encoding=UTF-8
# \u662F\u5426\u542F\u7528\u6A21\u677F\u7F13\u5B58\u529F\u80FD\uFF0C\u9ED8\u8BA4 true\u3002\u751F\u4EA7\u73AF\u5883\u6539\u4E3A true
spring.thymeleaf.cache=false
# \u5728SpringEL\u8868\u8FBE\u5F0F\u4E2D\u542F\u7528SpringEL\u7F16\u8BD1\u5668\uFF0C\u9ED8\u8BA4 false
spring.thymeleaf.enable-spring-el-compiler=true
# \u5199\u5165HTTP\u54CD\u5E94\u7684\u5185\u5BB9\u7C7B\u578B\u503C\uFF0C\u9ED8\u8BA4 text/html
spring.thymeleaf.servlet.content-type=text/html

############################################################
#
# i18n \u56FD\u9645\u5316\u914D\u7F6E
# @see MessageSourceProperties
#
############################################################
spring.messages.basename=i18n/messages
# \u52A0\u8F7D\u7684\u8D44\u6E90\u5305\u6587\u4EF6\u7F13\u5B58\u6301\u7EED\u65F6\u95F4\uFF0C\u9ED8\u8BA4\u6C38\u4E45\u7F13\u5B58\uFF0C\u5355\u4F4D\u79D2
spring.messages.cache-duration=3600

############################################################
#
# log \u914D\u7F6E
# https://www.cnblogs.com/bigben0123/p/7895696.html
# \u9ED8\u8BA4 logback \u914D\u7F6E\uFF1Aorg\springframework\boot\logging\logback\base.xml
#
############################################################
logging.file.name=logs/epitome.log
logging.level.root=info
logging.level.org.quartz=warn
# logging.level.org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping=trace
logging.level.org.springframework.boot.devtools=warn
logging.level.org.springframework.boot.autoconfigure.h2.H2ConsoleAutoConfiguration=warn
