spring.application.name=spring-boot-mqtt

# H2 Database Engine：https://h2database.com/html/main.html
# h2 数据库（内存模式）：https://www.cnblogs.com/TheoryDance/p/11941180.html
spring.datasource.driver-class-name=org.h2.Driver
# 内存数据库:<database_name>
spring.datasource.url=jdbc:h2:mem:test;MODE=MySQL;DB_CLOSE_DELAY=-1
spring.datasource.username=sa
spring.datasource.password=test
spring.sql.init.schema-locations=classpath:mqtt-schema.sql
spring.sql.init.data-locations=
# http://localhost:8080/h2-console
spring.h2.console.enabled=true

mybatis-plus.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl
mybatis-plus.configuration.map-underscore-to-camel-case=true
mybatis-plus.mapper-locations=classpath:mapper/*Mapper.xml

mqtt.username=ljh
mqtt.password=123
mqtt.url=tcp://192.168.119.128:1883
mqtt.subscribeClientId=sub_client_id_1
mqtt.subscribeTopics=ljh/iot/lamp/status
mqtt.publishClientId=pub_client_id_1
