server:
  port: 8126
  context-path: /tms8126

spring:
  dubbo:
    application:
      name: tms8126Provider
    registry:
      address: zookeeper://192.168.0.42:2181
#      address: zookeeper://172.20.200.149:2181
      file: cache/tms8126Provider.cache
#      file: ${user.home}/.dubbo/tms8126Provider.cache
    protocol:
      name: dubbo
      port: 20890
    scan: com.dayang.service

  datasource:
    tms:
      name: app
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
      url: jdbc:sqlserver://192.168.0.134;databasename=tms2
      username: test
      password: bpmlink
#      url: jdbc:sqlserver://172.20.200.138;databasename=tmsprd
#      username: tmsadmin
#      password: tmsadmin123
      # 初始化大小，最小，最大
      initialSize: 1
      minIdle: 1
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      # connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # 合并多个DruidDataSource的监控数据
      # useGlobalDataSourceStat: true
    eip:
      name: eip
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
      url: jdbc:sqlserver://192.168.0.134;databasename=eip12
      username: test
      password: bpmlink
#      url: jdbc:sqlserver://172.20.200.138;databasename=eip12
#      username: eipsa
#      password: eip1212
      initialSize: 1
      minIdle: 1
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      filters: stat
    ehr:
      name: ehr
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
      url: jdbc:sqlserver://192.168.0.153;databasename=jfchrms_zs
      username: sa
      password: 123456
#      url: jdbc:sqlserver://192.168.0.138;databasename=jfchrms_zs
#      username: ekpoms
#      password: ekpoms
      initialSize: 1
      minIdle: 1
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      filters: stat

#mybatis:
#  # 当mybatis的xml文件和mapper接口不在相同包下时，需要用mapperLocations属性指定xml文件的路径
#  mapper-locations: classpath:mapper/*.xml
#  # 在Mapper文件里面可以直接写对应的类名，而不用写全路径名
#  type-aliases-package: com.dayang.domain.eip, com.dayang.domain.app

logging:
  # 日志文件，绝对路径或相对路径
  file: logs/myspringboot.log
  # 保存日志文件目录路径
  path:
  # 日志配置文件，Spring Boot默认使用classpath路径下的日志配置文件，如:logback.xml
  config:
  # 日志级别：trace<debug<info<warn<error<fatal<off
  level:
    com.dayang: debug
    org.springfromework.web: info


