spring.application.name=spring-boot-mybatis
spring.config.import=optional:classpath:application-commons.properties

spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.url=jdbc:h2:mem:test;MODE=MySQL;DB_CLOSE_DELAY=-1
spring.datasource.username=sa
spring.datasource.password=
spring.sql.init.schema-locations=classpath:db/world-db/world-schema.sql
spring.sql.init.data-locations=classpath:db/world-db/world-data.sql
spring.h2.console.enabled=true

mybatis.mapper-locations=classpath:mapper/**/*.xml
# 指定类型别名包，XML 就无需写全限定类名
mybatis.type-aliases-package=org.ljh.mybatis.entity.normal
mybatis.type-handlers-package=org.ljh.mybatis.entity.handler
# 禁用日志输出
# mybatis.configuration.log-impl=org.apache.ibatis.logging.nologging.NoLoggingImpl
