spring.application.name=spring-boot-mybatis
spring.config.import=optional:classpath:application-commons.properties

spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.url=jdbc:h2:mem:test;MODE=MySQL;DB_CLOSE_DELAY=-1
spring.datasource.username=sa
spring.datasource.password=
spring.sql.init.schema-locations=classpath:db/world-db/world-schema.sql
spring.sql.init.data-locations=classpath:db/world-db/world-data.sql

mybatis.mapper-locations=classpath:mapper/**/*.xml
# 指定类型别名包，XML 就无需写全限定类名
mybatis.type-aliases-package=org.ljh.mybatis.entity.normal
mybatis.type-handlers-package=org.ljh.mybatis.entity.handler
# 数据库下划线命名 → 实体类驼峰命名
mybatis.configuration.map-underscore-to-camel-case=true
# 是否自动生成主键并回填
mybatis.configuration.use-generated-keys=true
# 是否开启二级缓存
mybatis.configuration.cache-enabled=false
# 是否延迟加载
mybatis.configuration.lazy-loading-enabled=true
# 是否激进延迟加载
#   true    对某一关联延迟加载属性的调用，都会触发其它所有关联属性的加载
#   false   默认
mybatis.configuration.aggressive-lazy-loading=false
# 设置默认语句超时时间；@Options(timeout = 60)
mybatis.configuration.default-statement-timeout=30
# 设置默认每次抓取数量；@Options(fetchSize = 20)
#   MySQL       0       一次性全部拉取到内存
#   PostgreSQL  0
#   SQL Server  0
#   Oracle      10      每次拉取10行，循环多次
mybatis.configuration.default-fetch-size=100
# 查询结果中 null 字段也调用 setter
mybatis.configuration.call-setters-on-nulls=true
# 空值 JDBC 类型（默认 Types.OTHER，Oracle 不认识）
mybatis.configuration.jdbc-type-for-null=NULL
# 禁用日志输出
# SLF4J → Jakarta Commons Logging → Log4j2 → Log4j → JDK logging → StdOut
# mybatis.configuration.log-impl=org.apache.ibatis.logging.nologging.NoLoggingImpl

# pagehelper：https://pagehelper.github.io/docs/howtouse/
pagehelper.helper-dialect=h2
# pageNumb <=0 返回第一页，pageNum >= pages 返回最后一页
pagehelper.reasonable=true
# 是否支持通过 Mapper 接口方法参数来传递分页参数
#   false   默认，必须通过 PageHelper.startPage(pageNum, pageSize) 显式开启分页
#   true    Mapper 接口方法参数中包含分页参数（如 pageNum、pageSize）时，自动进行分页
pagehelper.support-methods-arguments=true
# 分页参数与 Mapper 接口方法参数的映射配置
# 必须配合 support-methods-arguments=true 使用
#   默认 pageNum=pageNum&pageSize=pageSize
#   pageNum=pageNum     →   赋给当前页码
#   pageSize=pageSize   →   赋给每页条数
#   count=count         →   赋给是否执行 count 查询
pagehelper.params=pageNum=pageNum;pageSize=pageSize;count=count
