# https://github.com/apache/rocketmq-docker
# https://blog.csdn.net/oschina_41731918/article/details/123115102
version: '3.8'
networks:
  rocketmq_net:
    name: rocketmq_net
    driver: bridge
services:
  #Service for nameserver
  namesrv:
    image: apache/rocketmq
    container_name: rmqnamesrv
    ports:
      - 9876:9876
    volumes:
      - ./namesrv/logs:/home/rocketmq/logs
      - ./namesrv/store:/home/rocketmq/store
    environment:
      JAVA_OPT_EXT: "-Duser.home=/home/rocketmq -Xms512M -Xmx512M -Xmn128m"
    command: [ "sh","mqnamesrv" ]
    networks:
      rocketmq_net:
        aliases:
          - namesrv

  #Service for broker
  broker:
    image: apache/rocketmq
    container_name: rmqbroker
    ports:
      - 10909:10909
      - 10911:10911
    volumes:
      - ./broker/logs:/home/rocketmq/logs
      - ./broker/store:/home/rocketmq/store
      - ./broker/broker.conf:/etc/rocketmq/broker.conf
    environment:
      JAVA_OPT_EXT: "-Duser.home=/home/rocketmq -Xms512M -Xmx512M -Xmn128m"
    command: [ "sh","mqbroker","-c","/etc/rocketmq/broker.conf","-n","namesrv:9876","autoCreateTopicEnable=true" ]
    depends_on:
      - namesrv
    networks:
      rocketmq_net:
        aliases:
          - broker

  #Service for console
  console:
    image: styletang/rocketmq-console-ng
    container_name: rmqconsole
    ports:
      - 8180:8080
    environment:
      JAVA_OPTS: "-Drocketmq.namesrv.addr=namesrv:9876 -Dcom.rocketmq.sendMessageWithVIPChannel=false"
    depends_on:
      - namesrv
    networks:
      rocketmq_net:
        aliases:
          - console