# HTTP 负载均衡：https://docs.nginx.com/nginx/admin-guide/load-balancer/http-load-balancer/#method
# Nginx负载均衡-慕课网：
#   1 实现反向代理与集群高可用：https://www.imooc.com/video/23851
#   2 实现负载均衡：https://www.imooc.com/video/23860

# 定义一组服务器
# context: http
upstream www.ljh.com {
    # 4种负载均衡算法
    # ①                         轮询（默认）
    # ② least_conn              最少连接
    # ③ ip_hash                 根据客户端 IP 进行哈希，保证来自同一地址的请求到达同一服务器
    # ④ hash key [consistent]   根据 key 参数进行哈希，比 ip_hash 更灵活

    # weight=number
    # 设置服务器权重，默认1
    server  10.0.8.8:8081;
    server  10.0.8.8:8082 weight=2;
    server  10.0.8.8:8083 weight=3;
}

server {
    listen 	    80;
    server_name localhost;

    location / {
        proxy_pass 			http://www.ljh.com;
    }
}
