# 限制对代理 HTTP 资源的访问：https://docs.nginx.com/nginx/admin-guide/security-controls/controlling-access-proxied-http/
# ①Number of Connections    ngx_http_limit_conn_module      limit_conn_zone, limit_conn     限制连接数
# ②Request Rate             ngx_http_limit_req_module       limit_req_zone, limit_req       限制请求速率
# ③Bandwidth                ngx_http_core_module            limit_rate, limit_rate_after    限制宽带
